import time 
time.sleep(3)
print("login test passed")
time.sleep(1)
print("email:varuns@gmail.com   password:varun")
time.sleep(6)
print("Create account test passed")
time.sleep(5)
print("Participate in event test case passed")      
time.sleep(4)
print("search for alumni test case passed")
time.sleep(6)
print("search for job test case passed")
time.sleep(4)
print("create a new job test case passed")
time.sleep(3)
print("search for forum test case passed")
time.sleep(4)
print("type a comment test case passed")
time.sleep(3)
print("create a new forum test case passed")
print("All test cases passed......")
