name: PHP Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install PHP
      run: sudo apt-get install -y php
    - name: Lint PHP files
      run: |
        for file in $(find . -name "*.php"); do
          php -l $file
        done
