name: "Selenium Integration"

on:
  push:
    branches:
       - '*'
  pull_request:
    branches:
      - '*'
    types: [opened, synchronize, edited]

jobs:
  SeleniumJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install flake8 pytest
         pip install selenium
         pip install Service
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Selenium script
        run:  python finall_selenium.py
# name: Run Selenium tests

# on:
#   push:
#     branches:
#       - master

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     services:
#       selenium:
#         image: selenium/standalone-chrome:latest
#         ports:
#           - 4444:4444
#     steps:
#       - uses: actions/checkout@v2
#       - name: Install dependencies
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y python3 python3-pip
#           pip3 install selenium
#       - name: Run tests
#         run: |
#           python3 test.py
